# Generated by Django 2.1.1 on 2018-12-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='motto',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
