# Generated by Django 2.1.1 on 2018-12-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_articlesdetail_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesdetail',
            name='content_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlesdetail',
            name='content_md',
            field=models.TextField(blank=True),
        ),
    ]
