# Generated by Django 2.1.1 on 2018-12-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181204_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='comment_cont',
            new_name='comment_count',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='up_cont',
            new_name='up_count',
        ),
    ]
