# Generated by Django 2.1.1 on 2018-12-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181204_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='blog/avatars/default.png', upload_to='blog/avatars/', verbose_name='头像'),
        ),
    ]
