# Generated by Django 2.1.1 on 2018-12-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181205_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='blog/static/avatars/default.png', upload_to='blog/static/avatars/', verbose_name='头像'),
        ),
    ]
