# Generated by Django 2.1.1 on 2019-01-09 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181205_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesdetail',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
