# Generated by Django 2.1.1 on 2019-01-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190109_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlesDetail',
            new_name='ArticleDetail',
        ),
    ]
